language: node_js
node_js:
  - "8.10.0"
services:
  - postgresql
env:
 - SECRET=somesuperlongsecretkeyhere
  global:
  - CC_TEST_REPORTER_ID=c5fcf92b5da295120d8ce321fafb0f0f9748cad6da1077460ca315d1c6d44805
cache:
  directories:
    - "node_modules"

install:
  - npm install

before_script:
 - psql -c 'create database test_banka;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm run test
  
after_success:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT